In [1]:
import numpy as np 

In [2]:
x = np.array([2,4,3])
x

array([2, 4, 3])

In [3]:
(2**2 + 4**2 + 3**2)**(1/2)

5.385164807134504

In [4]:
np.linalg.norm(x)

5.385164807134504

In [5]:
x

array([2, 4, 3])

In [6]:
x = np.array([-2,4,3])

In [7]:
x

array([-2,  4,  3])

In [8]:
np.linalg.norm(x)

5.385164807134504

In [9]:
np.abs(-9)

9

In [10]:
x

array([-2,  4,  3])

In [11]:
np.abs(-2) + np.abs(4) + np.abs(3)

9

In [15]:
np.max([3,4,892,222])

892

In [16]:
np.max([np.abs(-2), np.abs(4), np.abs(3)])

4

## Squared L2 Norm

In [18]:
x 

array([-2,  4,  3])

In [22]:
((-2)**2 + 4**2 + 3**2)

29

In [23]:
np.dot(x, x)

29

In [27]:
x = np.array([3, 0])
x

array([3, 0])

In [28]:
y = np.array([0, 1])
y

array([0, 1])

In [29]:
np.dot(x, y)

0

In [30]:
x = np.array([[1,2], [3,4], [5,6]])

In [31]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
x.shape

(3, 2)

In [33]:
x.size

6

In [34]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
x[:,0]

array([1, 3, 5])

In [36]:
x[:,1]

array([2, 4, 6])

In [37]:
x[:2, :2]

array([[1, 2],
       [3, 4]])

In [38]:
x[1, :]

array([3, 4])