In [1]:
import numpy as np

In [6]:
arr = np.array([2,3,5,6], dtype = 'i')

In [7]:
arr

array([2, 3, 5, 6], dtype=int32)

In [8]:
type(arr)

numpy.ndarray

In [15]:
arr = np.array([1,2,3,4], np.int16)
print(arr)
np.shape(arr)

[1 2 3 4]


(4,)

In [12]:
arr

array([1, 2, 3, 4], dtype=int16)

In [13]:
np.shape(arr)

(4,)

In [17]:
np.shape(arr)

(4,)

In [20]:
arr.dtype

dtype('int16')

In [19]:
arr

array([1, 2, 3, 4], dtype=int16)

In [21]:
np.dtype

numpy.dtype

In [22]:
arr.dtype

dtype('int16')

In [23]:
arr = np.array((3,5,6,7))

In [24]:
arr

array([3, 5, 6, 7])

In [25]:
arr.dtype

dtype('int64')

In [30]:
arr = np.array({2,3,4,5,5,5})

In [31]:
arr

array({2, 3, 4, 5}, dtype=object)

In [32]:
arr.dtype

dtype('O')

In [35]:
np.ndim(arr)

0

In [36]:
arr = np.array((3,5,6,6))

In [37]:
np.ndim(arr)

1

In [40]:
np.shape(arr)

(4,)

In [49]:
new_arr = arr.resize(2,2)

In [50]:
arr

array([[3, 5],
       [6, 6]])

In [51]:
new_arr

In [52]:
arr

array([[3, 5],
       [6, 6]])

In [56]:
new_arr = arr.reshape(-1)

In [57]:
arr

array([[3, 5],
       [6, 6]])

In [58]:
new_arr

array([3, 5, 6, 6])

In [59]:
arr = new_arr

In [60]:
arr

array([3, 5, 6, 6])

In [61]:
new_arr

array([3, 5, 6, 6])

In [62]:
arr

array([3, 5, 6, 6])

In [63]:
arr[3]

6

In [65]:
arr[0]

3

In [70]:
zeros = np.zeros(8)

In [71]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
zeros.dtype

dtype('float64')

In [77]:
zeros.shape

(8,)

In [80]:
arr = np.zeros(4)

In [81]:
arr

array([0., 0., 0., 0.])

In [82]:
arr.dtype       [4, 0, 6],
       [7, 1, 0]])

dtype('float64')

In [86]:
arr = np.zeros((3,3))

In [87]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
zeros.dtype

dtype('float64')

In [89]:
zeros.shape

(8,)

In [90]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
arr.dtype

dtype('float64')

In [92]:
arr.shape

(3, 3)

In [93]:
arr.size

9

In [98]:
rng = np.arange(3,8,2)

In [99]:
rng

array([3, 5, 7])

In [100]:
lspace = np.linspace(1,10,8)

In [101]:
lspace

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [103]:
emp = np.empty((3,4))

In [104]:
emp

array([[9.81550189e-317, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [6.92852846e-310, 5.64812161e-038, 1.38326265e-047,
        1.14350506e-071],
       [3.56789385e-057, 8.93015679e+165, 1.51922112e-051,
        5.99248671e-038]])

In [112]:
ide = np.identity(9)

In [113]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [114]:
ide.shape

(9, 9)

In [115]:
ide.size

81

In [116]:
ide.dtype

dtype('float64')

In [117]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
arr = np.arange(1,13)

In [119]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [121]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [125]:
arr = arr.reshape(3,4)

In [126]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [127]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
arr.shape

(3, 4)

In [129]:
arr.size

12

In [130]:
arr.dtype

dtype('int64')

In [131]:
arr = arr.ravel()

In [132]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [134]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [135]:
arr = np.array(x)

In [136]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [139]:
type(x)

list

In [140]:
type(arr)

numpy.ndarray

In [141]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [142]:
arr.sum()

29

In [143]:
arr.sum(axis = 0)

array([12,  8,  9])

In [144]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [145]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [147]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [148]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [149]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [152]:
arr.flat

In [153]:
for x in arr.flat:
    print(x)

1
2
3
4
5
6
7
1
0


In [154]:
arr.ndim

2

In [155]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [156]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [157]:
arr.shape

(3, 3)

In [158]:
arr.size

9

In [159]:
arr.dtype

dtype('int64')

In [160]:
arr.ndim

2

In [162]:
arr.nbytes

72

In [164]:
arr.argmax()

6

In [165]:
arr.argmin()

8

In [166]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [168]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [169]:
one = np.array([1,3,4,634,2])

In [170]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [171]:
one

array([  1,   3,   4, 634,   2])

In [172]:
one.argmax()

3

In [173]:
one.argmin()

0

In [174]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [175]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [176]:
one

array([  1,   3,   4, 634,   2])

In [177]:
one.argsort()

array([0, 4, 1, 2, 3])

In [178]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [179]:
arr.argmax()

6

In [181]:
arr.argmax(axis = 1)

array([2, 2, 0])

In [184]:
arr.argmin(axis = 1)

array([0, 0, 2])

In [185]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [186]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [188]:
arr.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [189]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [190]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [191]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [192]:
arr.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [193]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [194]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [195]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [196]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [197]:
arr1 = arr

In [198]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [199]:
arr2 = np.array(arr1)

In [200]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [201]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [202]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [203]:
arr2[2,2] = 8

In [204]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [205]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [206]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  8]])

In [207]:
arr1 - arr2

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, -8]])

In [208]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [209]:
a1 = [2,3]
a2 = [5,6]

In [211]:
a1 + a2

[2, 3, 5, 6]

In [212]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [214]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [216]:
np.min(arr)

0

In [217]:
np.max(arr)

7

In [219]:
np.sum(arr)

29

In [220]:
np.sum(arr, axis = 1)

array([ 6, 15,  8])

In [221]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [222]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [223]:
type(np.where(arr > 5))

tuple

In [224]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [225]:
np.count_nonzero(arr)

8

In [226]:
arr[1,1] = 0

In [227]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [230]:
np.count_nonzero(arr)

7

In [231]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 2, 0, 1]))

In [232]:
np.__version__

'1.26.3'

In [233]:
import sys

In [235]:
sys.getsizeof(1)

28

In [236]:
py_ar = [2,3,4,5]

In [237]:
py_ar

[2, 3, 4, 5]

In [238]:
np_ar = np.array(py_ar)

In [239]:
np_ar

array([2, 3, 4, 5])

In [240]:
sys.getsizeof(np_ar[0])

32

In [241]:
sys.getsizeof(py_ar[0])

28

In [244]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [245]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [247]:
arr_list = arr.tolist()

In [248]:
arr_list

[[1, 2, 3], [4, 0, 6], [7, 1, 0]]

In [250]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])