In [160]:
arr = np.array([1,2,3,4] , np.int8)
arr
# print(arr.dtype)

array([1, 2, 3, 4], dtype=int8)

In [167]:
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)
print(arr.size)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
6
(2, 3)


In [170]:
arr = np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [191]:
arr2 = np.empty((4,6))
print(arr2)

[[2.41907520e-312 6.79038654e-313 6.79038653e-313 2.37663529e-312
  2.05833592e-312 2.41907520e-312]
 [2.56761491e-312 1.93101617e-312 9.33678148e-313 9.33678148e-313
  9.33678148e-313 1.97345609e-312]
 [9.33678148e-313 2.12199579e-312 2.56761491e-312 2.14321575e-312
  1.29441743e-312 8.27578359e-313]
 [2.33419537e-312 8.27578359e-313 2.12199579e-313 2.41907520e-312
  8.66554571e+140 4.10123933e+223]]


In [202]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [203]:
arr

array([0., 0., 0., 0., 0.])

In [204]:
arr = np.arange(12).reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [208]:
arr = arr.ravel()

In [209]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [210]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [211]:
arr.shape()

TypeError: 'tuple' object is not callable

In [212]:
arr.shape

(12,)

In [221]:
x = [[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]]
print(x)
print(type(x))
arr = np.array(x)
print(arr)
print(arr.size)
print(arr.ndim)
print(arr.shape)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
3
(2, 2, 3)


In [224]:
print(arr.sum(axis = 1))

[[ 5  7  9]
 [17 19 21]]
