In [19]:
import numpy as np

In [21]:
myarr = np.array([[2,3,4], [11,22,33], [30,40,50]], np.int16)

In [22]:
myarr

array([[ 2,  3,  4],
       [11, 22, 33],
       [30, 40, 50]], dtype=int16)

In [23]:
myarr[0,2]

4

In [24]:
myarr[2,1]

40

In [25]:
myarr.size

9

In [26]:
myarr.shape

(3, 3)

In [27]:
myarr.dtype

dtype('int16')

In [34]:
myarr2 = np.array((1,2,3), dtype = np.int8)

In [35]:
myarr2

array([1, 2, 3], dtype=int8)

In [39]:
arr = np.array({3,4,5})

In [40]:
arr

array({3, 4, 5}, dtype=object)

In [50]:
arr = np.zeros(4)

In [51]:
arr

array([0., 0., 0., 0.])

In [52]:
arr.size

4

In [53]:
arr.dtype

dtype('float64')

In [54]:
arr.shape

(4,)

In [55]:
arr = np.identity(4)

In [56]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
arr.size

16

In [58]:
arr.shape

(4, 4)

In [59]:
arr.dtype

dtype('float64')

In [61]:
arr = arr.reshape(8,2)

In [62]:
arr

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [63]:
arr.size

16

In [64]:
arr.dtype

dtype('float64')

In [65]:
arr.shape

(8, 2)

In [69]:
arr.ravel()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [70]:
arr

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [71]:
arr = arr.ravel()

In [72]:
arr

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [73]:
arr.size

16

In [74]:
arr.shape

(16,)

In [75]:
arr.dtype

dtype('float64')

In [78]:
arr = np.identity(8)

In [79]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
arr.size

64

In [81]:
arr.dtype

dtype('float64')

In [82]:
arr.shape

(8, 8)

In [84]:
arr[4,2]

0.0

In [85]:
arr2 = np.arange(33)

In [86]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [87]:
arr2.size


33

In [88]:
arr.shape

(8, 8)

In [89]:
arr2.shape

(33,)

In [90]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [95]:
arr2.reshape(11,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [96]:
arr2 = arr2.reshape(11,3)

In [98]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [99]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [100]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [101]:
arr = arr.ravel()

In [102]:
arr

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [105]:
arr3 = np.empty((4,5))

In [106]:
arr3

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69119873e-306, 1.78020848e-306],
       [8.90095411e-307, 1.78021798e-306, 6.23053614e-307,
        2.22522597e-306, 1.33511969e-306],
       [1.37962320e-306, 9.34604358e-307, 9.79101082e-307,
        1.78020576e-306, 1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306, 2.29178686e-312]])

In [112]:
arr3 = np.linspace(1,10,3)

In [113]:
arr3

array([ 1. ,  5.5, 10. ])