In [1]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6], dtype = 'i8')
print(arr)

[1 2 3 4 5 6]


In [15]:
print(arr.dtype)

int64


In [16]:
print(arr.shape)
print(arr.ndim)
print(arr.size)

(6,)
1
6


In [19]:
print(arr)
print(type(arr))
l = np.ndarray.tolist(arr)
print(l)
print(type(l))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


In [20]:
tup = (11,12,13,14,15)
arr = np.array(tup)
print(arr)
print(type(arr))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [51]:
arr = np.zeros((2,3), dtype = [('x', 'i1'),('y', 'i2'), ('z','i4')])
print(arr)
print(type(arr))
print(type(arr[0,0][0]))
print(type(arr[0,0][1]))

[[(0, 0, 0) (0, 0, 0) (0, 0, 0)]
 [(0, 0, 0) (0, 0, 0) (0, 0, 0)]]
<class 'numpy.ndarray'>
<class 'numpy.int8'>
<class 'numpy.int16'>


In [54]:
print(arr.dtype)
print(arr.size)
print(arr.shape)


[('x', 'i1'), ('y', '<i2'), ('z', '<i4')]
6
(2, 3)


In [61]:
arr = np.zeros(5)
print(arr)
print(arr.dtype)
arr2 = np.array(arr, dtype= 'i1')
print(arr2)
print(arr2.dtype)

[0. 0. 0. 0. 0.]
float64
[0 0 0 0 0]
int8
