In [11]:
import numpy as np

In [12]:
a = np.array(4) # 0D tensor or a scalar
print(a)
print(a.ndim)

4
0


In [13]:
arr = np.array([2,3,4,5]) # 1D Tensor, An array, 1D array, Vector
print(arr)
print(arr.ndim)

[2 3 4 5]
1


In [14]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]]) # matrix (collection of vector)
print(mat)
print(mat.ndim) # 2D Tensor

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
